name: Update IP List

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # 每 30 分钟运行一次（UTC 时间）

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        
    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global  user.email "github-actions[bot]@users.noreply.github.com"
        if [ -n "$(git status --porcelain)" ]; then
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          git add ip.txt
          git commit  -m "Automatic update at ${TIMESTAMP}"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
